server:
  port: 8084

logging:
  level:
    com.food.ordering.system: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
#    platform: postgres
#    initialization-mode: always
#    schema: classpath:init-schema.sql
#    data: classpath:init-data.sql
  sql:
    init:
      platform: postgres1
      schema-locations: classpath:/init-schema.sql
      data-locations: classpath:/init-data.sql
      mode: always

#spring.data.jpa.repositories.bootstrap-mode=default